name: Ruby

on: [push]

jobs:
  update_bundle:
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Date
      run: echo "::set-output name=date::$(date '+%Y_%m_%d')"
      id: current-date

    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle update
      run: |
        sudo apt -yqq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle update 

    - name: Commit
      run: |
        git config --global user.email "djurre.dejong@nedap.com"
        git config --global user.name "Djurre de jong"
        git checkout -b "bundle-update-${{ steps.current-date.outputs.date }}"
        git commit -am "Add updates"
        git push --set-upstream origin "bundle-update-${{ steps.current-date.outputs.date  }}"

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""
        destination_branch: "master"
        pr_title: "Full dependency update"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "Djurredejong"
        pr_assignee: "Djurredejong"
        pr_label: "Dependencies"
        github_token: ${{ secrets.GITHUB_TOKEN }}
