name: Ruby

on: [push]

jobs:
  update_bundle:
    runs-on: ubuntu-latest
    steps:
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      with:
        branch: bundle-update-${date +"%Y_%m_%d"}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle update
      run: |
        sudo apt -yqq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle update 

    - name: Commit
      uses: EndBug/add-and-commit@v2
      with: 
        commit_message: 'Apply automatic changes'
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
