name: Ruby

on: [push]

jobs:
  update_bundle:
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Date
      run: echo "::set-output name=date::$(date '+%Y_%m_%d')"
      id: current-date

    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      with:
        branch: bundle-update-${{ steps.current-date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle update
      run: |
        sudo apt -yqq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle update 

    - name: Commit
      run: |
        git config --global user.email "djurre.dejong@nedap.com"
        git config --global user.name "Djurredejong"
        git commit -am "Add updates"

    - name: Push Changes 
      uses: ad-m/github-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
